// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwMtgIoQpRm6QpDWQcShqJMabibx3JKF0',
    appId: '1:544105943195:web:69a9f0a254bad038f1763e',
    messagingSenderId: '544105943195',
    projectId: 'flutter-application-1-cf193',
    authDomain: 'flutter-application-1-cf193.firebaseapp.com',
    storageBucket: 'flutter-application-1-cf193.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoTbNEIJ7fQcw064wenD3KVPGzMnCDFuw',
    appId: '1:544105943195:android:93e921f2535bf11ef1763e',
    messagingSenderId: '544105943195',
    projectId: 'flutter-application-1-cf193',
    storageBucket: 'flutter-application-1-cf193.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwMtgIoQpRm6QpDWQcShqJMabibx3JKF0',
    appId: '1:544105943195:web:5b672d23b89763cff1763e',
    messagingSenderId: '544105943195',
    projectId: 'flutter-application-1-cf193',
    authDomain: 'flutter-application-1-cf193.firebaseapp.com',
    storageBucket: 'flutter-application-1-cf193.firebasestorage.app',
  );
}
